### ISSUE TITLE
Upgrade 0.27.3

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#275]
Ich brauche bitte eine Offerte für das Upgrade.
Beachtet dabei bitte, ass die Kosten für Upgrades auch durch die anderen Städte mitgetragen werden (gemäss Detailauflistung Kostenzusammenstellung decidim.swiss).
Merci

**Comment by bsantschi** [comment]
Offerte erstellt und an Nadja gesendet.

**Comment by Naadjjaa** [comment]
@bsantschi Ivan meint, wir sollten unbedingt die neuste Version 0.27.3 verwenden, da diese wichtige Security fixes enthält.

**Comment by Naadjjaa** [comment]
@carlobeltrame  "I'm happy to inform you that we made the official instructions for the reporting proposals. You can check it here: https://github.com/stadtluzern/decidim-letterbox-damagereporting. Also, will help developers which want to install the module". 
Bez. PDF sollte bis morgen Mittag die Version bereitstehen. Ich melde mich dann im anderen Ticket diesbezüglich nochmals.

**Comment by Naadjjaa** [comment]
@carlobeltrame Danke für das Update. Macht ihr Decidim Awesome auch noch auf die 0.27 Version? Wir warten seit dem Launch des Schadenmelders auf eine Funktion, die darin enthalten ist.

**Comment by carlobeltrame** [comment]
Fehler in decidim.swiss-spezifischen Code-Anpassungen, die noch behoben werden müssen bevor 0.27 funktionieren kann:
- [ ] https://sentry.puzzle.ch/pitc/decidim-luzern/issues/62923/
- [ ] https://sentry.puzzle.ch/pitc/decidim-luzern/issues/62924/
- [ ] https://sentry.puzzle.ch/pitc/decidim-luzern/issues/62921/

@Naadjjaa mit dem Upgrade kommt dann gleich die aktuellste Version von Decidim Awesome mit :+1:

**Comment by Kagemaru** [comment]
- [x] [Issue 62923](https://sentry.puzzle.ch/pitc/decidim-luzern/issues/62923/) ⇒ [Zürich Commit](https://github.com/puzzle/decidim-zuerich/commit/03a82c1912abba49d2ff7447097111d52be74727)
- [ ] [sentry.puzzle.ch/pitc/decidim-luzern/issues/62924](https://sentry.puzzle.ch/pitc/decidim-luzern/issues/62924/)
- [ ] [sentry.puzzle.ch/pitc/decidim-luzern/issues/62921](https://sentry.puzzle.ch/pitc/decidim-luzern/issues/62921/)

**Comment by larsUE** [comment]
Der File-Upload wirft derzeit noch einen Fehler -> egal was ich hochlade kommt immer "Fehler!" (hatten wir in Zürich ja auch).

**Comment by Naadjjaa** [comment]
@Kagemaru Das laden der Assemblies-Seite im Backend hat schon vorher lange gedauert, jetzt erhalte ich jedoch einen Serverfehler (Firefox & Chrome):


![Image](https://github.com/stadtluzern/decidim-ocl/assets/75797851/104192af-69bb-4d17-8d46-e65251da7151)

**Comment by innosmith** [comment]
@Kagemaru : die Anzeige von Veranstaltungen der Organisation "Klimaneutrale Region Oberland-Ost" führt zu einem Serverfehler:
https://test.deinklima.ch/assemblies/klimaneutraleregion/f/534/

**Comment by innosmith** [comment]
@Kagemaru : im Backend unter Benutzer gibt es neu die Menüoption "Admin Verantwortlichkeit". Ein Klick darauf von der deinklima-Testplattform listet Admins oder User aller Decidim-Tenants auf, siehe:
https://test.deinklima.ch/admin/decidim_awesome/admin_accountability

Insgesamt sind dies 37 Seiten von Admins oder Users inkl. Emailadressen. Das darf doch nicht sein? Ist das ein Feature speziell für Luzern entwickelt? Ich hoffe ihr könnt dies rasch ändern, bevor unsere Kund:innen aufschrecken bez. Datenschutz!

**Comment by innosmith** [comment]
@Kagemaru : das hinzufügen eines Profilbildes ergibt bei mir jeweils einen Fehler. Am kleinen Bild selbst sollte es nicht liegen, denn dieses habe ich schon öfter dafür verwendet.

Hier der direkte Link, getestet auf ImpulsKöniz und deinklima:
- https://test.impulskoeniz.ch/account
- https://test.deinklima.ch/account

**Comment by Kagemaru** [comment]
Ich fasse mal zusammen:

- [x] Bilder Upload ⇨ CORS Regeln angepasst
- [ ] Backend Assemblies
- [ ] Meetings von Organisationen
- [ ] Admin Verantwortlichkeiten
- [ ] Meetings Sortierung

**Comment by bsantschi** [comment]
Danke viu mau, Thomas! Betreffend "Admin Verantwortlichkeiten" warten wir auf einen Fix von Pokecode. @Naadjjaa hast du von Pokecode schon eine Antwort resp. den Fix erhalten?

**Comment by larsUE** [comment]
Datei Upload funktioniert wieder. Was mir noch auffällt ist, dass es nach wie vor missing translations hat, obwohl ich das Sprachfile schon länger auf dem aktuellen Stand habe (allerdings erst nachdem 0.27.3 erschienen ist). Vielleicht behebt sich das mit 0.27.4).

**Comment by Naadjjaa** [comment]
@carlobeltrame Ich finde "Navigation Maps" nicht mehr auf INT (bei den Blöcken für die Startseite). Ging dies vergessen?

**Comment by carlobeltrame** [comment]
@Naadjjaa @larsUE @innosmith die Integrationsumgebung von decidim.swiss ist jetzt auf Decidim 0.27.4.
Zusätzlich sind noch die aktuellsten Versionen der pokecode-Module drauf, und eine Version von navigation maps die mit 0.27 kompatibel sein müsste.
Als nächstes kümmere ich mich noch um die Karten-Integration.

**Comment by Naadjjaa** [comment]
@carlobeltrame @larsUE @innosmith Wir brauchen auch schon lange nur noch die Funktionen von Awesome für URL  & Links.

**Comment by Naadjjaa** [comment]
https://github.com/stadtluzern/decidim-ocl/issues/275#issuecomment-1649399937 Ich komme mittlerweile gar nicht mehr auf die Assemblies Seite im Backend, aufgrund des Timeouts. @bsantschi

**Comment by bsantschi** [comment]
Das Timeout mit den Assemblies wird in einem eigenen Ticket weiterverfolgt: https://github.com/decidim-swiss/decidim.swiss/issues/104
